# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Checklist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Checklist
  
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.9.0'
  pod 'FSCalendar'
  pod 'DropDown'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  
end
